export type Lang = "tr" | "en";

export const I18N = {
  tr: {
    nav: { works: "Eserler", about: "Hakkında", contact: "İletişim" },
    heroSubtitle: "Ressam — Suluboya, Çizim, Karışık Teknik",
    heroNote: "İstanbul'da yaşar ve çalışır.",
    scrollHint: "Eserler",
    selected: "Seçilmiş Eserler",
    period: "2023 — 2024",
    medium: "Medyum",
    theme: "Konu",
    worksCountSuffix: "eser",
    emptyState: "Bu seçim için eser bulunamadı.",
    aboutTitle: "Hakkında",
    aboutLead: "Aynı el, çok farklı odalar.",
    aboutBody: [
      "Ben Ahmet Emin Turgut. Resim yapıyorum — bazen Osmanlı bir konağın camına vuran akşam ışığını, bazen de bir buketin ardına saklanmış kafatasını.",
      "Çalışmam suluboya ve grafitin sessizliğinden, akriliğin patlamasına ve kömürün gravür yoğunluğuna kadar uzanır. Bana göre bu çelişki değil, aynı hayalin farklı sesleridir.",
      "Eserlerim Türkiye ve yurtdışında özel koleksiyonlardadır. Komisyon ve sergi taleplerine açığım.",
    ],
    portraitTag: "Portre — sanatçı fotoğrafı",
    bornLabel: "Doğum",
    bornValue: "1992, İstanbul",
    basedLabel: "Yaşadığı yer",
    basedValue: "İstanbul, Türkiye",
    practiceLabel: "Çalışma",
    practiceValue: "Resim, çizim, karışık teknik",
    contactTitle: "İletişim",
    contactLead: "Bir eser, bir komisyon, ya da yalnızca selam.",
    inquiryLabel: "Mesaj",
    nameField: "Adınız",
    emailField: "E-posta",
    msgField: "Mesajınız",
    send: "Gönder",
    sent: "Mesaj iletildi. Teşekkür ederim.",
    sendError: "Mesaj gönderilemedi, lütfen tekrar deneyin.",
    studioLabel: "Stüdyo",
    studioValue: "Beyoğlu, İstanbul",
    studioNote: "Randevu ile ziyaret",
    footerNote: "Tüm eserler © Ahmet Emin Turgut. İzinsiz kullanılamaz.",
    close: "Kapat",
    next: "Sonraki",
    prev: "Önceki",
    katalogTag: "Katalog",
    sizeLabel: "Boyut",
    navHint: "ok tuşları ile gezin · esc ile kapat",
  },
  en: {
    nav: { works: "Works", about: "About", contact: "Contact" },
    heroSubtitle: "Painter — Watercolor, Drawing, Mixed Media",
    heroNote: "Lives and works in Istanbul.",
    scrollHint: "Works",
    selected: "Selected Works",
    period: "2023 — 2024",
    medium: "Medium",
    theme: "Theme",
    worksCountSuffix: "works",
    emptyState: "No works for this selection.",
    aboutTitle: "About",
    aboutLead: "One hand, many rooms.",
    aboutBody: [
      "I am Ahmet Emin Turgut. I make paintings — sometimes the evening light against the window of an Ottoman house, sometimes the skull hiding behind a bouquet.",
      "My work moves between the quiet of watercolor and graphite, the burst of acrylic, and the engraving-like density of charcoal. To me these are not contradictions but different voices of the same dream.",
      "My pieces sit in private collections in Turkey and abroad. I am open to commissions and exhibition inquiries.",
    ],
    portraitTag: "Portrait — artist photograph",
    bornLabel: "Born",
    bornValue: "1992, Istanbul",
    basedLabel: "Based",
    basedValue: "Istanbul, Türkiye",
    practiceLabel: "Practice",
    practiceValue: "Painting, drawing, mixed media",
    contactTitle: "Contact",
    contactLead: "A work, a commission, or simply hello.",
    inquiryLabel: "Inquiry",
    nameField: "Your name",
    emailField: "Email",
    msgField: "Your message",
    send: "Send",
    sent: "Message received. Thank you.",
    sendError: "Could not send the message — please try again.",
    studioLabel: "Studio",
    studioValue: "Beyoğlu, Istanbul",
    studioNote: "By appointment",
    footerNote: "All works © Ahmet Emin Turgut. Used without permission is prohibited.",
    close: "Close",
    next: "Next",
    prev: "Previous",
    katalogTag: "Catalogue",
    sizeLabel: "Size",
    navHint: "arrow keys to navigate · esc to close",
  },
} as const;

export type Dictionary = (typeof I18N)["tr"];
